apache/flink-connector-jdbc

docs/content.zh/docs/connectors/table/jdbc.md, docs/content/docs/connectors/table/jdbc.md
A backport towards the v3.0 branch.
=> [FLINK-30357][doc] Wrong link in connector/jdbc doc. 

.github/workflows/push_pr.yml, .github/workflows/weekly.yml
The ci_utils workflow can now automatically infer the download URL and caching behavior. This implicitly switches stable binary downloads to archive.apache.org. This link will never expire; while the download speed is worse it shouldn't be a problem due to caching.
https://github.com/zentol/flink-connector-jdbc/actions/runs/4123496195/jobs/7121586447
=> [FLINK-30963][ci] Streamline binary URL configuration

docs/content.zh/docs/connectors/table/jdbc.md, docs/content/docs/connectors/table/jdbc.md
Fix wrong key 'lookup.cache.caching-missing-key' in 'jdbc.md'.
=> [FLINK-31437][docs] Fix wrong key 'lookup.cache.caching-missing-key' in 'jdbc.md'.

flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/catalog/AbstractJdbcCatalog.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/databases/postgres/catalog/PostgresCatalog.java
Currently the `PostgresCatalog#listTables()` creates a new connection and prepared statement for every schema and table when listing tables. This can be optimized by reusing those resources.
*(for example:)*
- Introduce `extractColumnValuesByStatement` in base class `AbstractJdbcCatalog`
- Reuse connection and prepared in `PostgresCatalog#listTables()`
This is moved from apache/flink#21146
=> [FLINK-29750][Connector/JDBC] Improve PostgresCatalog#listTables() by reusing resources

pom.xml
By default it inherints `flink.forkCountITCase` == 2 from flink.
The PR sets it to 1 
it looks sqlserver container has issues with starting in several surefire forks...
Based on https://github.com/MartijnVisser/flink-connector-jdbc/actions/runs/5265349453/jobs/9517854060
```
"main" #1 prio=5 os_prio=0 cpu=1965.96ms elapsed=2568.93s tid=0x00007f84a0027000 nid=0x1c82 runnable  [0x00007f84a41fc000]
java.lang.Thread.State: RUNNABLE
at java.net.SocketInputStream.socketRead0(java.base@11.0.19/Native Method)
at java.net.SocketInputStream.socketRead(java.base@11.0.19/SocketInputStream.java:115)
at java.net.SocketInputStream.read(java.base@11.0.19/SocketInputStream.java:168)
at java.net.SocketInputStream.read(java.base@11.0.19/SocketInputStream.java:140)
at …
```
=> [hotfix] Set fork count to 1 for IT cases

docs/content.zh/docs/connectors/table/jdbc.md, docs/content/docs/connectors/table/jdbc.md, flink-connector-jdbc/pom.xml, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/databases/trino/dialect/TrinoDialect.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/databases/trino/dialect/TrinoDialectFactory.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/databases/trino/dialect/TrinoRowConverter.java, flink-connector-jdbc/src/main/resources/META-INF/services/org.apache.flink.connector.jdbc.dialect.JdbcDialectFactory, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/databases/trino/TrinoTestBase.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/databases/trino/dialect/TrinoDialectTypeTest.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/databases/trino/dialect/TrinoPreparedStatementTest.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/databases/trino/table/TrinoDynamicTableSinkITCase.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/databases/trino/table/TrinoDynamicTableSourceITCase.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/internal/JdbcTableOutputFormatTest.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/table/JdbcDynamicTableSinkITCase.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/table/JdbcDynamicTableSourceITCase.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/testutils/databases/trino/TrinoDatabase.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/testutils/databases/trino/TrinoImages.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/testutils/databases/trino/TrinoMetadata.java
Add the implementation of the Trino dialect for JDBC connectors
Added:
TrinoDialect
TrinoDialectFactory
TrinoRowConverter
This change added tests and can be verified as follows:
- Added integration tests for end-to-end deployment 
- Some cases already covered with tests
- Dependencies (does it add or upgrade a dependency): (yes)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
- The serializers: (no)
- The runtime per-record code paths (performance sensitive): (no)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
- The S3 file system connector: (no)
- Does this pull request introduce a new feature? ( no)
- If yes, how is the feature documented? (docs)
=> [FLINK-15462][connectors] Add Trino dialect

flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/JdbcRowOutputFormat.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/JdbcSink.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/GenericJdbcSinkFunction.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/JdbcOutputFormat.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/JdbcOutputSerializer.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/RowJdbcOutputFormat.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/TableJdbcUpsertOutputFormat.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/executor/JdbcBatchStatementExecutor.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/executor/SimpleBatchStatementExecutor.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/executor/TableBufferReducedStatementExecutor.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/executor/TableBufferedStatementExecutor.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/JdbcDynamicTableSink.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/JdbcOutputFormatBuilder.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/JdbcXaSinkFunction.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/JdbcDataTestBase.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/JdbcRowOutputFormatTest.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/JdbcTestBase.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/internal/JdbcFullTest.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/internal/JdbcOutputSerializerTest.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/internal/JdbcTableOutputFormatTest.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/table/JdbcAppendOnlyWriterTest.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/table/JdbcDynamicTableSinkITCase.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/table/JdbcOutputFormatTest.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcXaSinkTestBase.java
This change is to remove the use of ExecutionConfig from JdbcOutputFormat, preparing the code for [SinkV2](https://issues.apache.org/jira/browse/FLINK-25421) with the changes introduced on 1.18 in [FLIP-287](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=240880853)
=> [FLINK-31332] Limit the use of ExecutionConfig on JdbcOutputFormat

.github/workflows/push_pr.yml, .github/workflows/weekly.yml, pom.xml
Changes made:
- downgrade flink version on pom to match rule of minimum supported version
- added validation on PRs for 1.16 (this is already on weekly)
- bump version from 1.18-SNAPSHOT to 1.18.0 on all gitactions
- bump the version of some test dependencies as Junit5, assertj, testcontainers and mockito
Note:
- version 1.19-SNAPSHOT is not added to CI because of [this](https://github.com/apache/flink-connector-jdbc/pull/76#issuecomment-1822864807)
=> [FLINK-33378] Prepare actions for flink version 1.18

.github/workflows/push_pr.yml, .github/workflows/weekly.yml, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/table/JdbcTablePlanTest.java
[FLINK-33883][jdbc] Bump CI flink version on flink-connector-jdbc to support flink 1.19.
=> [FLINK-33883][jdbc] Bump CI flink version on flink-connector-jdbc to support flink 1.19

.github/workflows/push_pr.yml, .github/workflows/weekly.yml, flink-connector-jdbc/pom.xml, pom.xml
The PR is to enable Java 17 checks for v3.1 (Flink 1.18)
this is a backport of https://github.com/apache/flink-connector-jdbc/pull/82
=> [FLINK-33952][FLINK-33787][jdbc] Java 17 support for jdbc connector

pom.xml
This is a follow up task for comments at https://github.com/apache/flink-web/pull/707#discussion_r1495584009
=> [hotfix] Use 1.16.0 as minimum supported Flink version in pom

flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/executor/TableBufferReducedStatementExecutor.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/executor/TableBufferedStatementExecutor.java
This PR adds a few checks to avoid sending empty buffer to database
=> [FLINK-34014][jdbc] Avoid executeBatch when buffer is empty

.github/workflows/push_pr.yml, .github/workflows/weekly.yml, pom.xml
The PR bumps flink-connector-parent to 1.1.0
and adds 1.20 to GHA
=> [hotfix] Update flink-connector-parent to 1.1.0

.github/workflows/push_pr.yml, .github/workflows/weekly.yml
The PR will allow to differentiate between jdbc connector statistics and others with name ci
=> [FLINK-34961] Use dedicated CI name for JDBC connector to differentiate it in infra-reports

.github/workflows/push_pr.yml, .github/workflows/weekly.yml
This is a cherry-picked backport of https://github.com/apache/flink-connector-jdbc/pull/112 to v3.1
=> [FLINK-34961][BP v3.1] Use dedicated CI name for JDBC connector to differentiate it in infra-reports

flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/JdbcConnectionOptions.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/catalog/AbstractJdbcCatalog.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/catalog/JdbcCatalog.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/catalog/JdbcCatalogUtils.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/catalog/factory/JdbcCatalogFactory.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/catalog/factory/JdbcCatalogFactoryOptions.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/databases/cratedb/catalog/CrateDBCatalog.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/databases/mysql/catalog/MySqlCatalog.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/databases/postgres/catalog/PostgresCatalog.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/JdbcDynamicTableFactory.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/utils/JdbcUtils.java
- Support property authentication connection for JDBC catalog & dynamic table
=> [FLINK-35176][Connector/JDBC] Support property authentication connection for JDBC catalog & dynamic table

flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/JdbcConnectionOptions.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/source/JdbcSourceBuilder.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/JdbcDynamicTableSource.java, flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/RowDataResultExtractor.java, flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/source/JdbcSourceBuilderTest.java
- Support the implementation of dynamic source tables based on the new source
=> [FLINK-33463][Connector/JDBC] Support the implementation of dynamic source tables based on the new source

flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/source/split/JdbcSourceSplitSerializer.java
- [FLINK-35542]  Use the class loader of class CheckpointedOffset while deserializing JdbcSourceSplit.
=> [FLINK-35542]  Set the correct class loader to lookup for the class CheckpointedOffset

docs/content.zh/docs/connectors/table/jdbc.md, docs/content/docs/connectors/table/jdbc.md, flink-connector-jdbc-core/src/main/java/org/apache/flink/connector/jdbc/core/table/FilterHandlingPolicy.java, flink-connector-jdbc-core/src/main/java/org/apache/flink/connector/jdbc/core/table/JdbcConnectorOptions.java, flink-connector-jdbc-core/src/main/java/org/apache/flink/connector/jdbc/core/table/JdbcDynamicTableFactory.java, flink-connector-jdbc-core/src/main/java/org/apache/flink/connector/jdbc/core/table/source/JdbcDynamicTableSource.java, flink-connector-jdbc-core/src/test/java/org/apache/flink/connector/jdbc/core/table/JdbcDynamicTableFactoryTest.java, flink-connector-jdbc-core/src/test/java/org/apache/flink/connector/jdbc/core/table/JdbcTablePlanTest.java, flink-connector-jdbc-core/src/test/java/org/apache/flink/connector/jdbc/core/table/source/JdbcDynamicTableSourceITCase.java, flink-connector-jdbc-core/src/test/resources/org/apache/flink/connector/jdbc/core/table/JdbcTablePlanTest.xml
This improvement implements [FLIP-377 Support fine-grained configuration to control filter push down for Table/SQL Sources](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=276105768)
=> [FLINK-34215] FLIP-377: Support fine-grained configuration to control filter push down for JDBC Connector

pom.xml
Remove redundant maven properties with upgrade of flink-connector-parent to 1.1.0
=> [hotfix] Remove redundant maven properties with upgrade of flink-connector-parent to 1.1.0

flink-connector-jdbc-core/src/main/java/org/apache/flink/connector/jdbc/internal/JdbcOutputFormat.java
An SQL Server sink connector may fail with the following exception:
```
java.io.IOException: Writing records to JDBC failed.
at org.apache.flink.connector.jdbc.internal.JdbcOutputFormat.writeRecord(JdbcOutputFormat.java:198)
at org.apache.flink.connector.jdbc.internal.GenericJdbcSinkFunction.invoke(GenericJdbcSinkFunction.java:57)
at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:54)
at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82)
at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:68)
at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:62)
at org.apache.flink.streaming.api.operators.LegacyKeyedProcessOperato …
```
=> [FLINK-36051] Re-prepare invalid statement even if connection is valid

flink-connector-jdbc-core/src/test/java/org/apache/flink/connector/jdbc/core/datastream/source/JdbcSourceStreamRelatedITCase.java
Add timeout for test case that call [JdbcSourceStreamRelatedITCase#waitExpectation](https://github.com/apache/flink-connector-jdbc/blob/15c1a78d79c3b060ac544ae9bfce13befe3d3ee0/flink-connector-jdbc-core/src/test/java/org/apache/flink/connector/jdbc/core/datastream/source/JdbcSourceStreamRelatedITCase.java#L225).
=> [FLINK-37234] Add test timeout to avoid  infinite waiting.

flink-connector-jdbc-postgres/src/main/java/org/apache/flink/connector/jdbc/postgres/database/dialect/PostgresDialect.java, flink-connector-jdbc-postgres/src/test/java/org/apache/flink/connector/jdbc/postgres/database/dialect/PostgresDialectTest.java
In PostgreSQL, there is no need to specify the unique key fields in the `DO UPDATE SET` clause.
See more details in https://www.postgresql.org/docs/current/sql-insert.html
=> [hotfix][Connector/JDBC] Remove unnecessary unique fields of PostgreSQL upsert statement
